version: '3'
services:
  trader-server:
    container_name: "trader-backend"
    build: .
    environment:
        - MONGODB_URL=mongodb://tradermongo:27017/traderapp
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - tradermongo
    links:
      - tradermongo
  tradermongo:
    image: mongo
    container_name: "tradermongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null
